### ISSUE TITLE
Sometimes testing data downloads timeout

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKIOOpenSlide#6]
Some of the large testing data downloads timeout.  This should be resolved by this patch:

  http://review.source.kitware.com/#/c/21016/

@nslay please review the patch in Gerrit.  After merged, we can update the testing Docker image.

**Comment by nslay** [comment]
Hi Matthew,
All of it looks good to me. Should I sign up for Gerrit?

Best regards,
Nathan Lay

**Comment by nslay** [comment]
By the way, I'm on vacation where I'm fishing 8-9 hours a day. It will delay my responses. But it keeps me away from the computer.

Tomorrow is my last day of fishing.

**Comment by thewtex** [comment]
Hi Nathan,

Best of luck fishing! Hopefully they have started to bite :-)

Yes, it would be great if you signed up for Gerrit -- your GitHub account will work to log in. Next steps are to make this module available in ITK as a Remote module:

  http://www.itk.org/Wiki/ITK/Policy_and_Procedures_for_Adding_Remote_Modules

after creating a short Insight Journal article:

  http://insight-journal.org/
  https://github.com/InsightSoftwareConsortium/InsightJournalTemplate

Best,
Matt

**Comment by nslay** [comment]
Don't worry. I didn't forget about the Insight Journal article.

**Comment by thewtex** [comment]
Excellent :8ball: 

Closing this issue since we fixed the data download issue.
